#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "There needs to be a bucket name"
    exit 1
fi

BUCKET_NAME=$1

#varianta 1
aws s3api list-objects-v2 --bucket "$BUCKET_NAME" --query 'Contents[].Key' --output json > object_keys.json

jq -r '.[]' object_keys.json | while read OBJECT_KEY; do
    echo "Deleting: $OBJECT_KEY"
    aws s3api delete-object --bucket "$BUCKET_NAME" --key "$OBJECT_KEY"
done

rm -rf object_keys.json

#varianta 2
# aws s3api list-objects-v2 \
#     --bucket "$BUCKET_NAME" \
#     --query 'Contents[].Key' \
#     | jq -n '{Objects: [inputs | .[] | {Key: .}]}' > /tmp/delete_objects.json

# aws s3api delete-objects --bucket "$BUCKET_NAME" --delete file:///tmp/delete_objects.json

